// Flashcard vocabulary: original definitions and examples for this project.
// 6 decks, ~20 words each, covering the vocabulary that shows up across the
// 12 TOEFL task families (academic reading/listening plus campus-life and
// connector vocabulary useful for Writing and Speaking).

// mode: '' = word -> meaning; 'produce' = Russian -> type the English;
// 'fix' = type the corrected sentence (word = wrong, def = right, ex/ru = rule).
export const DECKS = [
  { id: 'mistakes', name: 'Fix the mistake', blurb: 'Real errors from practice emails and discussions. Type the correct sentence, then check.', mode: 'fix' },
  { id: 'articles', name: 'Articles: a / an / the / —', blurb: 'Fill the gaps. Rules from Destination C1 Unit 21 (Noun phrases), with Russian explanations.', mode: 'fix' },
  { id: 'c1-grammar', name: 'Destination C1 grammar', blurb: 'Two key rules from every grammar unit of Destination C1 & C2, as fix-the-sentence cards.', mode: 'fix' },
  { id: 'phrases', name: 'Phrases RU → EN', blurb: 'Active recall: see the Russian, produce the English. Words and templates for Email, Discussion and Interview.', mode: 'produce' },
  { id: 'pronunciation', name: 'Pronunciation', blurb: 'Stress and TH sounds. Say the word out loud first, then press 🔊 and compare.' },
  { id: 'mine', name: 'My words', blurb: 'Words you add yourself while working through the books.', mode: 'produce' },
  { id: 'academic-verbs', name: 'Academic verbs', blurb: 'Verbs that show up constantly in academic reading, lectures and your own writing.' },
  { id: 'academic-nouns', name: 'Academic nouns', blurb: 'Concepts common in research papers, lectures and Academic Discussion prompts.' },
  { id: 'science-nature', name: 'Science & nature', blurb: 'Vocabulary from biology, earth science and environmental reading passages.' },
  { id: 'society-history', name: 'Society & history', blurb: 'Terms from history, politics and social-science reading passages.' },
  { id: 'campus-life', name: 'Campus life', blurb: 'Everyday words from Read in Daily Life and campus Conversation listening tasks.' },
  { id: 'linking', name: 'Linking words', blurb: 'Connectors that make Writing and Speaking responses read as one coherent argument.' },
];

function slug(word) {
  return word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function deck(id, pos, rows) {
  return rows.map(([word, def, ex, ru]) => ({ id: `${id}-${slug(word)}`, deck: id, word, pos, def, ex, ru }));
}

function fixDeck(id, rows) {
  return rows.map(([pos, word, def, ex, ru]) => ({ id: `${id}-${slug(word).slice(0, 48)}`, deck: id, word, pos, def, ex, ru }));
}

const mistakes = fixDeck('mistakes', [
  ['email', 'Dear, Professor', 'Dear Professor Brown,', 'No comma after "Dear"; put the comma after the name. Use the surname if you know it.', 'После Dear запятой нет; запятая после имени.'],
  ['email', 'I faced a post that the university is planning a festival.', 'I came across a post saying that the university is planning a festival.', 'face = deal with a problem. come across = find by chance.', 'face — столкнуться с проблемой; случайно наткнуться — come across.'],
  ['email', 'My close friend has applied the request to be a volunteer.', 'My close friend has applied to be a volunteer.', 'apply to do something; apply for something (a job, a program).', 'apply for + сущ., apply to + глагол.'],
  ['email', 'I am very curious to spend my winter holidays there.', 'I am eager to spend my winter holidays there.', 'curious = want to know. eager / keen = really want to do.', 'curious — любопытно узнать; хочу сделать — eager to.'],
  ['email', 'This exam is too important for me.', 'This exam is extremely important for me.', '"too" means more than is good. For emphasis use very / extremely.', 'too = «слишком» (плохо). Для усиления — very / extremely.'],
  ['email', "This situation would be okay if I wouldn't have an exam.", "This situation would be fine if I didn't have an exam.", 'Second conditional: if + past simple, would + verb. Never "would" in the if-clause.', 'В if-части нет would: if I didn\'t have…, it would be…'],
  ['email', 'I will be so glad if you could accept my suggestion.', 'I would be very grateful if you could accept my suggestion.', 'Polite request: I would be grateful if you could…', 'Вежливо: I would be grateful if you could… (would, не will).'],
  ['email', 'Could I run over to some free dormitory nearby?', 'Could I temporarily move to another dormitory nearby?', '"run over" = hit with a car. Use move to / stay in.', 'run over — «переехать машиной». Нужно move to / stay in.'],
  ['email', 'Could you share us the reasons for canceling the event?', 'Could you share the reasons for canceling the event with us?', 'share something WITH someone.', 'share что-то with кем-то (не share us).'],
  ['email', 'It took us all out of time and effort.', 'It took us a lot of time and effort.', 'Fixed phrase: a lot of time and effort.', 'Устойчиво: a lot of time and effort.'],
  ['email', 'It is even witnessed by Guiness Record.', 'It was even recognized by Guinness World Records.', 'Past event, so past tense. "recognized", not "witnessed". Spelling: Guinness World Records.', 'Событие в прошлом → was. «Зафиксирован» = recognized.'],
  ['email', 'I have about 250+ hours experience in volunteering.', 'I have over 250 hours of volunteering experience.', 'hours OF experience. Don\'t use "about" and "+" together.', 'hours of experience; about и + вместе не ставим.'],
  ['email', 'The total engagement increased twice after my work.', 'Total engagement doubled after I joined the team.', '"increased twice" = it went up on two occasions. Use doubled / tripled.', '«выросло в 2 раза» = doubled.'],
  ['email', 'Nowadays, I am preparing for my qualification exam.', 'Currently, I am preparing for my qualification exam.', 'nowadays = in modern society. For your own situation: currently / at the moment.', 'nowadays — «в наше время» (про общество). Про себя — currently.'],
  ['email', 'This is my third attempt, so this year I was preparing very seriously.', 'This is my third attempt, so this year I have been preparing very seriously.', 'From the past until now → present perfect continuous.', 'С прошлого до сих пор → have been preparing.'],
  ['email', 'I was trying to update the website and turn off my Wifi.', 'I tried refreshing the page and restarting my Wi-Fi.', 'refresh a page (update = install a new version). Finished attempts → past simple. Spelling: Wi-Fi.', 'Обновить страницу = refresh. Разовые попытки → past simple.'],
  ['email', 'It all started yesterday morning, around 9pm.', 'It all started yesterday morning, at around 9 a.m.', 'Morning = a.m. Check your details: raters notice contradictions.', 'Утро = a.m. Проверяй логику деталей.'],
  ['email', 'The first letter has been written by professor Ms.Sarah.', 'The first letter was written by Professor Johnson.', 'Title + surname, capital P. Don\'t combine "Professor" and "Ms."', 'Professor + фамилия, с большой буквы. Professor и Ms. вместе нельзя.'],
  ['email', 'I was your student from my philosophy course, during last year in Princeton.', 'I was a student in your philosophy course at Princeton last year.', 'a student in your course; AT a university; no preposition before "last year".', 'at Princeton; last year — без предлога.'],
  ['email', 'I received an email that tomorrow my dormitory will be closed.', 'I received an email saying that my dormitory would be closed for two days.', 'After a past reporting verb, will → would.', 'После прошедшего (received, said) — would вместо will.'],
  ['email', 'I want to know how other chefs are cooking regular.', 'I want to know how other chefs usually cook.', 'Habits → present simple + usually (an adverb, not the adjective "regular").', 'Привычка → present simple + usually.'],
  ['email', 'I suggest to your team to add some activities.', 'I suggest that your team add some activities.', 'suggest + -ing, or suggest that + subject + verb. Never "suggest someone to do".', 'suggest doing / suggest that…; НЕ suggest sb to do.'],
  ['email', 'I am professional at organizing festivals.', 'I would consider myself experienced at organizing festivals.', '"professional" = it is your paid job. Don\'t overclaim; "consider myself" sounds natural.', 'Не преувеличивай: consider myself experienced.'],
  ['discussion', 'Both Liam and Emma suggested absolutely great points of view.', 'Both Liam and Emma make valid points.', 'make a point / raise a point. Avoid over-the-top words like "absolutely great".', 'make a valid point — устойчиво.'],
  ['discussion', 'From one side Student A is also right.', 'On the one hand, Student A is right that AI can help.', 'Pair: On the one hand… On the other hand…', 'Пара: On the one hand… / On the other hand…'],
  ['discussion', "Social media's negative effect outwards the benefits.", 'The negative effects of social media outweigh the benefits.', 'outweigh = be more important than.', 'outweigh — перевешивать.'],
  ['discussion', 'Higher taxes is the only way.', 'Higher taxes are the only way.', 'Plural subject → plural verb.', 'Подлежащее во мн. числе → are.'],
  ['discussion', 'Some factories pollute the nature.', 'Some factories pollute the environment.', '"nature" as a concept takes no article; "the environment" always takes "the".', 'nature — без артикля; the environment — с the.'],
  ['discussion', 'Someone who studied in Harvard could do it faster.', 'Someone who studied at Harvard could do it faster.', 'study AT a university. Most university names take no article.', 'at Harvard, без the.'],
  ['discussion', 'Companies require employees to have a long experience.', 'Companies require employees to have many years of experience.', 'experience (опыт) is uncountable, so no "a". "an experience" = one event.', 'experience = опыт — неисчисляемое, без a.'],
  ['discussion', "People's willings to leave the job increase.", "People's willingness to leave their jobs increases.", 'willingness is the noun; it is singular → increases.', 'willingness — существительное, ед. ч. → increases.'],
  ['discussion', 'As Student B shared, a country\'s identity is important.', 'As Student A pointed out, traditional languages are part of a country\'s identity.', 'Check who said what. Mixing up the students shows you did not read carefully.', 'Проверь, кто что сказал. Путаница = минус баллы.'],
  ['discussion', 'Students choose regular food rather than healthy one.', 'Students choose cheap food rather than healthy food.', '"one" replaces countable nouns only. "food" is uncountable here, so repeat the noun.', 'one заменяет только исчисляемые; food — повтори слово.'],
  ['discussion', "It doesn't mean that this person does complete the tasks effectively.", "It doesn't mean that this person completes tasks effectively.", 'No "does" in a normal statement; it is only for emphasis.', 'does перед глаголом — только для эмфазы.'],
  ['discussion', 'In the future they might have some troubles with well-being.', 'In the future, they might develop health problems.', 'Be specific: health problems. "troubles" is rarely plural.', 'Конкретнее: health problems.'],
  ['speaking', 'It was, like, really hard, like, I could not sleep.', 'It was really hard. For example, I could not sleep.', 'Drop filler "like". For examples use "for example" or "such as".', 'Без «like» как слова-паразита. Пример: for example / such as.'],
]);

const articles = fixDeck('articles', [
  ['a / an', 'I came across ___ post about ___ international festival.', 'I came across a post about an international festival.', 'First mention, one of many → a/an. "an" before a vowel sound.', 'Первое упоминание → a/an; an — перед гласным звуком.'],
  ['the', 'This is one of ___ most prestigious programs in ___ world.', 'This is one of the most prestigious programs in the world.', 'Superlatives and unique things take "the".', 'Превосходная степень и единственное в своём роде → the.'],
  ['a / an', 'I am ___ undergraduate student at ___ Rice University.', 'I am an undergraduate student at Rice University.', '"an" before a vowel sound. "X University" usually takes no article.', 'an undergraduate; Rice University — без артикля.'],
  ['the', 'I study at ___ University of Toronto.', 'I study at the University of Toronto.', '"The University of X" takes "the".', 'The University of … → the.'],
  ['places', 'People in ___ USA can message people in ___ Kazakhstan in seconds.', 'People in the USA can message people in Kazakhstan in seconds.', 'Countries take no article, except names with States / Kingdom / Republic or plurals.', 'Страны без артикля; но the USA, the UK, the Netherlands.'],
  ['the', '___ deadline is ___ 9th of October.', 'The deadline is the 9th of October.', 'A specific thing you both know → the. Ordinal dates → the 9th.', 'Конкретное → the; даты: the 9th of October.'],
  ['zero', '___ healthy food is ___ important source of vitamins.', 'Healthy food is an important source of vitamins.', 'An uncountable noun in general → no article. "an" before "important".', 'Неисчисляемое в общем смысле → без артикля.'],
  ['zero', '___ students need ___ proper nutrition.', 'Students need proper nutrition.', 'Plural or uncountable nouns in general → no article.', 'Обобщение (мн. ч. / неисчисляемое) → без артикля.'],
  ['the', '___ students in my group want cheaper meals.', 'The students in my group want cheaper meals.', 'A specific group ("in my group") → the.', 'Конкретная группа → the.'],
  ['zero', 'I want to gain ___ experience in ___ software engineering.', 'I want to gain experience in software engineering.', 'experience (опыт) and fields of study take no article.', 'Опыт и области знаний — без артикля.'],
  ['a / an', 'Volunteering at the hackathon was ___ amazing experience.', 'Volunteering at the hackathon was an amazing experience.', 'experience = one event (впечатление) is countable → an.', 'experience = случай/впечатление → an.'],
  ['the', '___ university is considering changing ___ food options in the cafeteria.', 'The university is considering changing the food options in the cafeteria.', 'The particular university and options you both know → the.', 'Известный обоим → the.'],
  ['zero', '___ technology has changed ___ way we communicate.', 'Technology has changed the way we communicate.', 'An abstract idea in general → no article. "the way we…" is made specific by the clause.', 'Абстракция без артикля; the way we…'],
  ['phrases', 'On ___ one hand, AI helps students. On ___ other hand, it can make them lazy.', 'On the one hand, AI helps students. On the other hand, it can make them lazy.', 'Fixed phrases.', 'Устойчиво: On the one hand / On the other hand.'],
  ['phrases', 'In ___ future, more classes will be online.', 'In the future, more classes will be online.', 'Fixed: in the future, in the past.', 'in the future / in the past — всегда the.'],
  ['zero', 'I usually go to ___ work by ___ bus.', 'I usually go to work by bus.', 'go to work / school / bed; by + transport → no article.', 'go to work, by bus — без артикля.'],
  ['the', 'He plays ___ guitar and ___ football.', 'He plays the guitar and football.', 'Instruments take "the"; sports take no article.', 'Инструменты → the; спорт → без.'],
  ['a / an', 'I got ___ email from ___ IT department.', 'I got an email from the IT department.', '"an" before a vowel SOUND (an email, an IT…). Your university\'s department → the.', 'По звуку: an email, an IT; конкретный отдел → the.'],
  ['a / an', 'She is ___ honest person and ___ university professor.', 'She is an honest person and a university professor.', 'Sound, not letter: an honest (silent h), a university ("yu").', 'По звуку: an honest, a university.'],
  ['zero', '___ Japan is famous for ___ sushi.', 'Japan is famous for sushi.', 'Country → no article; uncountable food in general → no article.', 'Страна и еда в общем — без артикля.'],
  ['the', '___ government should protect ___ environment.', 'The government should protect the environment.', 'the government (of your country), the environment (fixed).', 'the government, the environment.'],
  ['possessive', 'I spent ___ summer holidays volunteering.', 'I spent my summer holidays volunteering.', 'Russian has no articles, so you often need my / our / their here.', 'Часто нужен my/our, а не артикль.'],
  ['the', '___ social media is becoming ___ main way of communication.', 'Social media is becoming the main way of communication.', 'General concept → no article. main / only / same → the.', 'main / only / same → the.'],
  ['a / the', 'I had ___ problem with ___ website yesterday.', 'I had a problem with the website yesterday.', 'a problem (first mention); the website (the course platform you already mentioned).', 'Новое → a; уже известное → the.'],
  ['a / an', 'Most people want ___ high salary.', 'Most people want a high salary.', '"salary" is countable → a high salary.', 'salary — исчисляемое → a.'],
  ['zero', 'Most of ___ people around the world use AI.', 'Most people around the world use AI.', 'most + noun = in general. "most of the" only for a specific group (most of the people in my class).', 'most people (вообще) vs most of the people in my class.'],
  ['the', '___ elderly need more support from the state.', 'The elderly need more support from the state.', 'the + adjective = a group of people (the rich, the poor, the young).', 'the + прилагательное = группа людей.'],
  ['a / an', 'This is ___ unique opportunity.', 'This is a unique opportunity.', '"unique" starts with a "yu" sound → a.', 'a unique — звук «ю».'],
  ['countable', 'Could you give me ___ advice about the exam?', 'Could you give me some advice about the exam?', 'advice, information, news, research, equipment, furniture are uncountable: no "a", no plural.', 'advice, information, news — неисчисляемые: some / a piece of.'],
]);

const c1Grammar = fixDeck('c1-grammar', [
  ['Unit 1 · present', 'I am knowing the answer.', 'I know the answer.', 'State verbs (know, believe, own, belong, seem) are not normally used in continuous forms.', 'Глаголы состояния без -ing.'],
  ['Unit 1 · present', 'I study at this university since 2024.', 'I have been studying at this university since 2024.', 'since / for + an action still going on → present perfect (continuous).', 'since/for + до сих пор → have been studying.'],
  ['Unit 3 · past', 'When I arrived, the lecture already started.', 'When I arrived, the lecture had already started.', 'The earlier of two past actions → past perfect.', 'Более раннее из двух прошлых действий → had + V3.'],
  ['Unit 3 · past', 'I used to living in a dormitory.', 'I used to live in a dormitory.', 'used to + verb = past habit. be used to + -ing = be accustomed.', 'used to do — раньше; be used to doing — привык.'],
  ['Unit 5 · future', 'I will call you when I will arrive.', 'I will call you when I arrive.', 'After when / as soon as / before / until → present simple for the future.', 'После when/as soon as — present simple.'],
  ['Unit 5 · future', 'By next June I will finish my degree.', 'By next June I will have finished my degree.', 'by + future time → future perfect.', 'by + время в будущем → will have done.'],
  ['Unit 7 · passive', 'The experiment conducted in 2020.', 'The experiment was conducted in 2020.', 'Passive = be + past participle.', 'Пассив = be + V3.'],
  ['Unit 7 · causative', 'I cut my hair yesterday at the barber.', 'I had my hair cut yesterday.', 'Someone else did it for you → have/get + object + past participle.', 'Сделал не сам → have something done.'],
  ['Unit 9 · modals', 'You must to submit the form today.', 'You must submit the form today.', 'Modals + bare infinitive (no "to").', 'После модальных — без to.'],
  ['Unit 9 · modals', 'He should have came earlier.', 'He should have come earlier.', 'Past criticism / regret: should have + past participle.', 'should have + V3 (сожаление о прошлом).'],
  ['Unit 11 · conditionals', 'If I would know the answer, I would tell you.', 'If I knew the answer, I would tell you.', 'Second conditional: if + past simple, would + verb.', 'if + past, would + verb.'],
  ['Unit 11 · conditionals', 'If I had studied harder, I would pass the exam last year.', 'If I had studied harder, I would have passed the exam last year.', 'Third conditional: if + past perfect, would have + past participle.', 'if + had done, would have done.'],
  ['Unit 11 · conditionals', 'If I took that job last year, I would be richer now.', 'If I had taken that job last year, I would be richer now.', 'Mixed conditional: past condition (had done) → present result (would be).', 'Смешанное: прошлое условие → результат сейчас.'],
  ['Unit 13 · unreal time', 'I wish I have more time to prepare.', 'I wish I had more time to prepare.', 'wish + past simple = regret about the present.', 'wish + past = жаль, что сейчас не так.'],
  ['Unit 13 · unreal time', "It's time we start studying seriously.", "It's time we started studying seriously.", "It's (high) time + subject + past simple.", "It's time + past simple."],
  ['Unit 15 · adverbs', 'She speaks English very good.', 'She speaks English very well.', 'Verbs are described by adverbs: well, not good.', 'Глагол описывает наречие: well.'],
  ['Unit 15 · adjectives', 'The lecture was boring and I was boring too.', 'The lecture was boring and I was bored.', '-ing = what causes the feeling; -ed = how you feel.', '-ing — что вызывает; -ed — что я чувствую.'],
  ['Unit 15 · adjectives', 'This task is enough difficult.', 'This task is difficult enough.', 'adjective + enough; enough + noun.', 'difficult enough; enough time.'],
  ['Unit 17 · clauses', 'The student which won the prize is from Kazakhstan.', 'The student who won the prize is from Kazakhstan.', 'who for people, which for things.', 'who — люди, which — предметы.'],
  ['Unit 17 · clauses', 'Kazakhstan, that is the largest landlocked country, has huge steppes.', "Kazakhstan, which is the world's largest landlocked country, has huge steppes.", 'Non-defining clauses (between commas) use which / who, never that.', 'С запятыми — which/who, не that.'],
  ['Unit 19 · complex', 'Despite it was raining, we went out.', 'Although it was raining, we went out.', 'although + clause; despite / in spite of + noun or -ing (despite the rain).', 'although + предложение; despite + сущ./-ing.'],
  ['Unit 19 · complex', 'Because of the prices are high, students eat junk food.', 'Because prices are high, students eat junk food.', 'because + clause; because of + noun (because of high prices).', 'because + предложение; because of + сущ.'],
  ['Unit 19 · inversion', 'Not only it is cheap, but also it is healthy.', 'Not only is it cheap, but it is also healthy.', 'Not only at the start of a sentence → question word order.', 'Not only в начале → инверсия: is it.'],
  ['Unit 21 · nouns', 'The news are good.', 'The news is good.', 'news, physics, politics end in -s but take a singular verb.', 'news — ед. ч.: is.'],
  ['Unit 23 · verb patterns', "I'm looking forward to hear from you.", "I'm looking forward to hearing from you.", 'look forward to + -ing ("to" is a preposition here).', 'look forward to + -ing.'],
  ['Unit 23 · verb patterns', 'Students should avoid to use AI for whole essays.', 'Students should avoid using AI for whole essays.', 'avoid / consider / enjoy / mind / suggest + -ing.', 'avoid/consider/enjoy + -ing.'],
  ['Unit 23 · verb patterns', 'The professor made us to rewrite the essay.', 'The professor made us rewrite the essay.', 'make / let + object + bare infinitive.', 'make/let somebody do — без to.'],
  ['Unit 25 · reporting', 'He said me that the event was cancelled.', 'He told me that the event was cancelled.', 'say (something); tell someone (something).', 'say что-то; tell кому-то.'],
  ['Unit 25 · reporting', 'She asked where is the library.', 'She asked where the library was.', 'Reported questions use statement word order.', 'В косвенном вопросе — прямой порядок слов.'],
  ['Unit 25 · reporting', 'The professor explained me the rule.', 'The professor explained the rule to me.', 'explain something TO someone.', 'explain что-то to кому-то.'],
]);

const phrases = [
  ...deck('phrases', 'word', [
    ['most likely', 'very probably', 'The workshop will most likely be postponed until spring.', 'скорее всего'],
    ['come across', 'to find or see something by chance', 'It is easy to come across fake news online.', 'наткнуться, случайно найти'],
    ['consider myself', 'to think of yourself as', 'I consider myself a responsible and organized person.', 'считаю себя'],
    ['eager to', 'really wanting to do something', 'I am eager to join the exchange program.', 'очень хочу, стремлюсь'],
    ['extensive experience', 'a lot of experience (no "a")', 'She has extensive experience in event management.', 'большой опыт'],
    ['scrutinize', 'to examine very carefully', 'Governments should scrutinize how other countries regulate AI.', 'тщательно изучать'],
    ['outweigh', 'to be greater or more important than', 'In my view, the benefits of online learning outweigh the drawbacks.', 'перевешивать'],
    ['expenditure', 'the amount of money spent', 'Poor health leads to higher medical expenditure.', 'расходы'],
    ['doubled', 'became twice as big', 'Engagement on our page doubled after the campaign.', 'выросло вдвое'],
    ['willingness', 'being ready to do something', 'Employers value a willingness to learn.', 'готовность'],
    ['conceal', 'to hide (often feelings)', 'People often try to conceal their emotions at work.', 'скрывать'],
    ['reveal', 'to show something hidden', 'Facial expressions can reveal how a person really feels.', 'раскрывать, выдавать'],
    ['prevent', 'to stop something from happening', 'Regular exercise can prevent many health problems.', 'предотвращать'],
    ['suppress', 'to stop yourself from showing a feeling', 'It is unhealthy to suppress your anger all the time.', 'подавлять'],
    ['viewpoint', 'a way of thinking about a subject', 'Both students present a reasonable viewpoint.', 'точка зрения'],
    ['phenomenon', 'something that happens and can be observed (pl. phenomena)', 'Remote work is a relatively new phenomenon.', 'явление'],
    ['irrational', 'not based on reason', 'Many fears, such as the fear of flying, are irrational.', 'иррациональный'],
    ['independently', 'without help from others', 'Some students can learn the material independently.', 'самостоятельно'],
    ['harmful', 'causing damage', "Junk food can be harmful to students' health.", 'вредный'],
    ['alternative', 'another possible choice', 'Could you suggest an alternative date for the workshop?', 'альтернатива, другой вариант'],
    ['indicate', 'to show or suggest', 'Crossed arms may indicate that a person feels defensive.', 'указывать на'],
    ['occur', 'to happen', 'Most accidents occur at home.', 'происходить'],
    ['universal', 'shared by everyone', 'A smile is a universal sign of friendliness.', 'всеобщий, универсальный'],
    ['precise', 'exact and accurate', 'Engineers need precise measurements before they dig.', 'точный'],
    ['excavate', 'to dig in the ground', 'Workers had to excavate the street to repair the pipelines.', 'раскапывать'],
    ['currently', 'at the moment (about you, not society)', 'I am currently preparing for my qualification exam.', 'в настоящее время (про себя)'],
    ['refresh the page', 'to reload a website', 'I tried to refresh the page, but the button still did not work.', 'обновить страницу'],
    ['such as', 'use for examples instead of "like"', 'Students could join activities such as mini soccer games.', 'такие как (вместо like)'],
  ]),
  ...deck('phrases', 'email', [
    ['I hope this email finds you well', 'friendly first line', 'Dear Professor Brown, I hope this email finds you well.', 'Надеюсь, у вас всё хорошо (начало письма)'],
    ['I am writing to', 'state your purpose in the first lines', 'I am writing to ask about volunteer opportunities.', 'Пишу, чтобы… (цель письма)'],
    ['I would be grateful if you could', 'polite request', 'I would be grateful if you could extend the deadline.', 'Буду благодарен, если вы сможете…'],
    ['I was wondering whether', 'soft, polite question', 'I was wondering whether the workshop will be rescheduled.', 'Хотел узнать, не… (мягкий вопрос)'],
    ['I look forward to hearing from you', 'closing line before the sign-off', 'Thank you for your time. I look forward to hearing from you.', 'Жду вашего ответа'],
  ]),
  ...deck('phrases', 'discussion', [
    ['raises a valid point', 'agree with a classmate', 'Emma raises a valid point about nutrition.', 'приводит веский довод'],
    ['I see why', 'show you understand the other side before disagreeing', 'I see why Liam supports cheaper meals, but health matters more.', 'Понимаю, почему… (перед возражением)'],
    ['a clear example of this is', 'introduce one specific example', "A clear example of this is my university's cafeteria.", 'Яркий пример этого —'],
    ['for these reasons', 'start your conclusion', 'For these reasons, I believe universities should prioritize healthy food.', 'По этим причинам (вывод)'],
  ]),
  ...deck('phrases', 'speaking', [
    ["That's an interesting question", 'buy two seconds instead of "uhm" or "like"', "That's an interesting question. I think it depends on the person.", 'Интересный вопрос (выиграть время)'],
    ['The main reason is that', 'give your reason right after your answer', 'The main reason is that students have limited budgets.', 'Главная причина в том, что…'],
    ['To sum up', 'one-sentence wrap-up before time runs out', 'To sum up, I would choose the job I enjoy.', 'Подводя итог'],
  ]),
];

const pronunciation = [
  ...deck('pronunciation', 'stress', [
    ['important', 'im-POR-tant  /ɪmˈpɔːr.tənt/', 'It is important to practice every day.', 'Ударение на POR: имПОРтант.'],
    ['during', 'DUR-ing  /ˈdʊr.ɪŋ/', 'I studied during the break.', 'Коротко «дУринг», не «дьююринг».'],
    ['prevent', 'pre-VENT  /prɪˈvent/', 'Vaccines prevent serious illness.', 'Ударение на второй слог.'],
    ['technicians', 'tech-NI-cians  /tekˈnɪʃ.ənz/', 'The technicians fixed the pipes.', 'Ударение на NI.'],
    ['excavating', 'EX-ca-vat-ing  /ˈek.skə.veɪ.tɪŋ/', 'They are excavating the old road.', 'Ударение на первый слог.'],
    ['precise', 'pre-CISE  /prɪˈsaɪs/', 'Give a precise answer.', 'Конец — глухое s, не z.'],
    ['underground', 'UN-der-ground  /ˈʌn.dər.ɡraʊnd/', 'The cables run through an underground tunnel.', 'Ударение на UN.'],
    ['districts', 'DIS-tricts  /ˈdɪs.trɪkts/', 'Several districts lost power.', 'Произнеси все согласные в конце: -kts.'],
    ['conceal', 'con-CEAL  /kənˈsiːl/', 'She tried to conceal her surprise.', 'Первая гласная слабая: кэн-СИЛ.'],
    ['phenomenon', 'phe-NOM-e-non  /fəˈnɑː.mə.nɑːn/', 'This phenomenon is common in deserts.', 'Ударение на NOM.'],
    ['environment', 'en-VI-ron-ment  /ɪnˈvaɪ.rən.mənt/', 'We must protect the environment.', 'Ударение на VI («вай»).'],
    ['alternative', 'al-TER-na-tive  /ɔːlˈtɝː.nə.tɪv/', 'Is there an alternative route?', 'Ударение на TER.'],
    ['evaluation', 'e-val-u-A-tion  /ɪˌvæl.juˈeɪ.ʃən/', 'The evaluation takes two weeks.', 'Главное ударение на A («эй»).'],
    ['occur', 'oc-CUR  /əˈkɝː/', 'Earthquakes occur without warning.', 'Ударение на второй слог.'],
    ['indicate', 'IN-di-cate  /ˈɪn.də.keɪt/', 'The results indicate a clear trend.', 'Ударение на IN.'],
    ['utilities', 'u-TIL-i-ties  /juːˈtɪl.ə.tiz/', 'Rent includes utilities.', 'Ударение на TIL.'],
    ['universal', 'u-ni-VER-sal  /ˌjuː.nəˈvɝː.səl/', 'Music is a universal language.', 'Ударение на VER.'],
    ['comfortable', 'COMF-ter-ble  /ˈkʌmf.tər.bəl/', 'The dormitory is quite comfortable.', 'Три слога, не «комфОРтабл».'],
    ['development', 'de-VEL-op-ment  /dɪˈvel.əp.mənt/', 'Economic development takes time.', 'Ударение на VEL.'],
  ]),
  ...deck('pronunciation', 'th', [
    ['think', '/θɪŋk/  voiceless TH: tongue between the teeth, blow air', 'I think online classes are useful.', 'Язык между зубами, дуй. Не «синк» и не «финк».'],
    ['three', '/θriː/  voiceless TH', 'There are three main reasons.', 'Не «сри» и не «фри».'],
    ['through', '/θruː/  voiceless TH', 'I learned it through practice.', 'Язык между зубами.'],
    ['thought', '/θɑːt/  voiceless TH', 'I thought about it carefully.', 'Не «сот».'],
    ['method', 'METH-od  /ˈmeθ.əd/', 'This method saves time.', 'TH в середине слова тоже межзубный.'],
    ['health', '/helθ/  TH at the end', 'Sleep is important for your health.', 'В конце — межзубный, не «хелс».'],
    ['growth', '/ɡroʊθ/  TH at the end', 'The city saw rapid growth.', 'В конце — межзубный.'],
    ['therefore', 'THERE-fore  /ˈðer.fɔːr/  voiced TH', 'Therefore, I agree with Emma.', 'Звонкий: язык между зубами + голос. Не «зэа» и не «дэа».'],
    ['although', 'al-THOUGH  /ɔːlˈðoʊ/  voiced TH', 'Although it is expensive, it is worth it.', 'Ударение на второй слог, звонкий TH.'],
    ['the', '"thuh" /ðə/ before consonants, "thee" /ði/ before vowel sounds', 'The end of the lecture was the best part.', 'the book [ðə], the end [ði].'],
  ]),
];

const academicVerbs = deck('academic-verbs', 'v.', [
  ['analyze', 'to examine something in detail to understand it', 'Researchers analyzed the survey data to find a pattern.', 'анализировать'],
  ['assume', 'to accept something as true without proof', 'The study assumes that all participants answered honestly.', 'предполагать'],
  ['derive', 'to obtain something from a source', 'The formula is derived from basic physics principles.', 'выводить, получать'],
  ['demonstrate', 'to show something clearly by giving proof', 'The experiment demonstrates that heat speeds up the reaction.', 'демонстрировать'],
  ['contradict', 'to say the opposite of, or conflict with', 'The new findings contradict the earlier theory.', 'противоречить'],
  ['emphasize', 'to give special importance to something', 'The professor emphasized the importance of citing sources.', 'подчёркивать'],
  ['illustrate', 'to make something clear by using an example', 'The graph illustrates how prices rose over a decade.', 'иллюстрировать'],
  ['indicate', 'to point out or show something', 'A rising temperature indicates that the reaction is exothermic.', 'указывать'],
  ['infer', 'to reach a conclusion based on evidence', 'From the data, we can infer that the drug is effective.', 'делать вывод'],
  ['interpret', 'to explain the meaning of something', 'Different scholars interpret the poem in very different ways.', 'истолковывать'],
  ['justify', 'to show that something is reasonable', 'The team must justify their conclusion with clear evidence from the experiment.', 'обосновывать'],
  ['mitigate', 'to make something less severe', 'New regulations aim to mitigate the effects of pollution.', 'смягчать'],
  ['obtain', 'to get something, especially through effort', 'Researchers obtained permission before starting the interviews.', 'получать'],
  ['persist', 'to continue to exist despite difficulty', 'The symptoms persisted even after treatment.', 'сохраняться, упорствовать'],
  ['reinforce', 'to strengthen or support something further', 'The second experiment reinforced the results of the first.', 'подкреплять'],
  ['resolve', 'to find a solution to a problem', 'The committee resolved the dispute after a long debate.', 'разрешать'],
  ['undermine', 'to weaken something gradually', 'Constant interruptions undermined the speaker’s argument.', 'подрывать'],
  ['validate', 'to confirm that something is correct', 'A second test validated the original findings.', 'подтверждать'],
  ['differentiate', 'to recognize a difference between things', 'The course teaches students to differentiate fact from opinion.', 'различать'],
  ['correlate', 'to have a mutual relationship with something', 'Higher education levels correlate with higher income.', 'коррелировать'],
]);

const academicNouns = deck('academic-nouns', 'n.', [
  ['hypothesis', 'an idea proposed as a basis for testing', 'The scientist tested her hypothesis in the lab.', 'гипотеза'],
  ['methodology', 'a system of methods used in a study', 'The paper explains the methodology used to collect data.', 'методология'],
  ['phenomenon', 'a fact or event that can be observed', 'Global warming is a phenomenon studied by climatologists.', 'явление'],
  ['variable', 'a factor that can change in an experiment', 'Temperature was the only variable the team controlled.', 'переменная'],
  ['criterion', 'a standard used to judge or decide something', 'Punctuality is one criterion for the award.', 'критерий'],
  ['framework', 'a basic structure underlying a system or theory', 'The report uses a theoretical framework from sociology.', 'структура, каркас'],
  ['paradigm', 'a typical example or accepted pattern of thinking', 'This discovery created a new paradigm in biology.', 'парадигма'],
  ['correlation', 'a mutual relationship between two or more things', 'There is a strong correlation between exercise and sleep quality.', 'взаимосвязь'],
  ['implication', 'a likely consequence of something', 'The findings have important implications for public policy.', 'следствие, вывод'],
  ['bias', 'a tendency to favor one view unfairly', 'The survey questions showed a clear bias.', 'предвзятость'],
  ['consensus', 'general agreement among a group', 'Scientists reached a consensus on the cause of the outbreak.', 'консенсус'],
  ['discrepancy', 'a difference between things that should match', 'There was a discrepancy between the two reports.', 'расхождение'],
  ['synthesis', 'the combination of ideas or parts to form a whole', 'Her essay is a synthesis of three different theories.', 'синтез'],
  ['premise', 'a statement that forms the basis of an argument', 'The argument’s premise turned out to be false.', 'предпосылка'],
  ['inference', 'a conclusion reached on the basis of evidence', 'The inference was based on limited data.', 'умозаключение'],
  ['controversy', 'public disagreement about a topic', 'The policy sparked controversy among voters.', 'спор, полемика'],
  ['mechanism', 'a process by which something happens', 'Scientists studied the mechanism behind muscle fatigue.', 'механизм'],
  ['anomaly', 'something that deviates from what is normal', 'The satellite detected an anomaly in the data.', 'аномалия'],
  ['cohort', 'a group of people sharing a common characteristic', 'The study followed a cohort of 500 students.', 'когорта'],
  ['trajectory', 'the path something follows as it develops over time', 'The report predicts the economy’s trajectory for the decade.', 'траектория'],
]);

const scienceNature = deck('science-nature', 'n.', [
  ['ecosystem', 'a community of organisms and their environment', 'Coral reefs are one of the richest ecosystems on Earth.', 'экосистема'],
  ['biodiversity', 'the variety of life found in a particular area', 'Rainforests contain an enormous amount of biodiversity.', 'биоразнообразие'],
  ['habitat', 'the natural home of an organism', 'Deforestation destroys the habitat of many species.', 'среда обитания'],
  ['extinction', 'the dying out of a species', 'Overhunting led to the extinction of the passenger pigeon.', 'вымирание'],
  ['evolution', 'gradual change in species over generations', 'Darwin’s theory of evolution explains how species adapt.', 'эволюция'],
  ['mutation', 'a change in an organism’s genetic material', 'A random mutation can sometimes give an organism an advantage.', 'мутация'],
  ['photosynthesis', 'the process plants use to make food from light', 'Photosynthesis converts sunlight into chemical energy.', 'фотосинтез'],
  ['metabolism', 'the chemical processes that maintain life in an organism', 'A faster metabolism burns calories more quickly.', 'обмен веществ'],
  ['molecule', 'the smallest unit of a chemical compound', 'Water is made of hydrogen and oxygen molecules.', 'молекула'],
  ['catalyst', 'a substance that speeds up a chemical reaction', 'Enzymes act as catalysts in digestion.', 'катализатор'],
  ['sediment', 'solid material deposited by water, ice or wind', 'Layers of sediment reveal the region’s geological history.', 'осадок, отложение'],
  ['erosion', 'the gradual wearing away of land by wind or water', 'Coastal erosion has removed several meters of beach.', 'эрозия'],
  ['tectonic', 'relating to the structure of the Earth’s crust', 'Tectonic plates shift slowly over millions of years.', 'тектонический'],
  ['precipitation', 'rain, snow or other water falling from clouds', 'The region receives little precipitation each year.', 'осадки'],
  ['drought', 'a long period of unusually low rainfall', 'The drought severely reduced the wheat harvest.', 'засуха'],
  ['glacier', 'a large mass of slowly moving ice', 'The glacier has retreated significantly over the past decade.', 'ледник'],
  ['emission', 'a substance released into the air', 'Factories must reduce their carbon emissions.', 'выброс'],
  ['conservation', 'the protection of the natural environment', 'The park was created for wildlife conservation.', 'охрана природы'],
  ['predator', 'an animal that hunts other animals for food', 'Wolves are the main predator in this forest.', 'хищник'],
  ['adaptation', 'a change that helps an organism survive in its environment', 'Thick fur is an adaptation to cold climates.', 'адаптация'],
]);

const societyHistory = deck('society-history', 'n.', [
  ['civilization', 'an advanced, organized human society', 'The Nile supported one of the earliest civilizations.', 'цивилизация'],
  ['colonization', 'the act of settling and controlling another territory', 'European colonization changed the map of the Americas.', 'колонизация'],
  ['revolution', 'a sudden, major change, often political', 'The industrial revolution transformed how goods were made.', 'революция'],
  ['monarchy', 'a system of government ruled by a king or queen', 'Britain remains a constitutional monarchy today.', 'монархия'],
  ['democracy', 'a system of government by the people', 'Ancient Athens is often called the birthplace of democracy.', 'демократия'],
  ['dynasty', 'a series of rulers from the same family', 'The Ming dynasty ruled China for nearly 300 years.', 'династия'],
  ['diplomacy', 'the management of relations between countries', 'The crisis was resolved through diplomacy, not war.', 'дипломатия'],
  ['treaty', 'a formal agreement between two or more states', 'The two countries signed a peace treaty.', 'договор'],
  ['sovereignty', 'the authority of a state to govern itself', 'The colony finally gained full sovereignty in 1960.', 'суверенитет'],
  ['artifact', 'an object made by humans, often of historical interest', 'Archaeologists found pottery artifacts at the site.', 'артефакт'],
  ['archaeology', 'the study of human history through excavation', 'Archaeology reveals how ancient people actually lived.', 'археология'],
  ['heritage', 'traditions and achievements passed down from the past', 'The old town is protected as a cultural heritage site.', 'наследие'],
  ['ideology', 'a set of political or social beliefs', 'The party’s ideology shaped its economic policy.', 'идеология'],
  ['propaganda', 'biased information used to influence opinion', 'The regime used propaganda to control public opinion.', 'пропаганда'],
  ['inequality', 'an unfair difference between groups', 'Income inequality has grown in many countries.', 'неравенство'],
  ['urbanization', 'the growth of cities as people move there', 'Rapid urbanization strained the city’s infrastructure.', 'урбанизация'],
  ['immigrant', 'a person who moves to live permanently in another country', 'Many immigrants arrived seeking better opportunities.', 'иммигрант'],
  ['refugee', 'a person forced to flee their country', 'The war created millions of refugees.', 'беженец'],
  ['activism', 'action taken to bring about social or political change', 'Student activism played a key role in the movement.', 'активизм'],
  ['industrialization', 'the development of industry on a large scale', 'Industrialization brought both jobs and pollution to the region.', 'индустриализация'],
]);

const campusLife = deck('campus-life', 'n.', [
  ['registrar', 'the university office that manages student records', 'You need to contact the registrar to change your major.', 'деканат / отдел регистрации'],
  ['transcript', 'an official record of a student’s grades', 'Send your transcript to the admissions office.', 'зачётная книжка / выписка оценок'],
  ['tuition', 'the fee charged for instruction at a school', 'Tuition at the university rose again this year.', 'плата за обучение'],
  ['scholarship', 'money awarded to support a student’s studies', 'She received a full scholarship to study engineering.', 'стипендия'],
  ['prerequisite', 'a course that must be completed before taking another', 'Calculus I is a prerequisite for this class.', 'обязательное условие / предмет'],
  ['syllabus', 'a document outlining a course’s content and rules', 'Check the syllabus for the exam date.', 'учебный план курса'],
  ['elective', 'an optional course a student may choose to take', 'She picked photography as her elective this term.', 'элективный курс'],
  ['dormitory', 'a building where students live on campus', 'Most first-year students live in a dormitory.', 'общежитие'],
  ['orientation', 'an introductory program for new students', 'Orientation week helps students find their way around campus.', 'вводный курс / ориентация'],
  ['advisor', 'a staff member who guides a student’s studies', 'Meet your advisor before registering for classes.', 'научный руководитель / куратор'],
  ['thesis', 'a long piece of research written to earn a degree', 'He is writing his thesis on renewable energy.', 'дипломная работа'],
  ['dissertation', 'a lengthy piece of research for an advanced degree', 'Her dissertation took three years to complete.', 'диссертация'],
  ['internship', 'temporary work experience related to one’s studies', 'The internship gave her real experience in the field.', 'стажировка'],
  ['faculty', 'the teaching staff of a university', 'The faculty voted to change the course requirements.', 'профессорско-преподавательский состав'],
  ['tutorial', 'a small class focused on discussion or practice', 'The tutorial helped clarify the lecture material.', 'семинар / практическое занятие'],
  ['plagiarism', 'presenting someone else’s work as your own', 'Plagiarism can lead to serious academic penalties.', 'плагиат'],
  ['citation', 'a reference to a source used in academic writing', 'Every quote needs a proper citation.', 'цитирование / ссылка'],
  ['waitlist', 'a list of people waiting for a spot to open up', 'She was on the waitlist for the popular seminar.', 'список ожидания'],
  ['semester', 'one of the two main terms of an academic year', 'Grades are posted at the end of each semester.', 'семестр'],
  ['alumni', 'former students of a school or university', 'Many alumni return each year for homecoming.', 'выпускники'],
]);

const linking = deck('linking', 'connector', [
  ['however', 'introducing a contrast with what was just said', 'The plan was well designed; however, it failed in practice.', 'однако'],
  ['nevertheless', 'despite what was just said, still', 'The results were disappointing; nevertheless, the team kept working.', 'тем не менее'],
  ['moreover', 'used to add a further point', 'The policy is expensive; moreover, it has proven ineffective.', 'более того'],
  ['furthermore', 'used to add another, often stronger, point', 'The data is incomplete. Furthermore, it was collected inconsistently.', 'кроме того'],
  ['consequently', 'as a result of what was just said', 'Sales dropped sharply; consequently, the store closed.', 'следовательно'],
  ['therefore', 'for that reason', 'The evidence is weak; therefore, the theory needs revision.', 'поэтому'],
  ['whereas', 'used to compare two facts that are different', 'City rent is high, whereas rural rent is much lower.', 'тогда как'],
  ['although', 'despite the fact that', 'Although the test was hard, most students passed.', 'хотя'],
  ['nonetheless', 'even so, despite what was just said', 'It rained all day; nonetheless, the event continued.', 'тем не менее'],
  ['meanwhile', 'at the same time as something else', 'The team ran tests; meanwhile, the client waited for updates.', 'тем временем'],
  ['subsequently', 'afterward, at a later time', 'He failed the first attempt but subsequently passed the exam.', 'впоследствии'],
  ['accordingly', 'in a way that fits or follows from the situation', 'Prices rose, and consumers adjusted their spending accordingly.', 'соответственно'],
  ['likewise', 'in the same way, similarly', 'The first study found no effect; likewise, the second confirmed it.', 'аналогично'],
  ['conversely', 'showing the opposite point of view', 'Rich soil produces high yields; conversely, poor soil produces little.', 'наоборот'],
  ['specifically', 'referring to one particular thing in more detail', 'The report focuses specifically on rural education.', 'в частности'],
  ['essentially', 'in the most basic or fundamental sense', 'The two theories are essentially the same.', 'по сути'],
  ['ultimately', 'in the end, after everything is considered', 'The negotiations were long but ultimately successful.', 'в конечном счёте'],
  ['admittedly', 'used to accept that something is true before adding a point', 'Admittedly, the method has some flaws.', 'по общему признанию'],
  ['arguably', 'used to say something can be reasonably argued', 'This is arguably the most important finding in the study.', 'можно утверждать'],
  ['in contrast', 'showing a clear difference between two things', 'Northern regions are cold; in contrast, the south stays warm year-round.', 'в противоположность'],
]);

export const VOCAB = [
  ...mistakes,
  ...articles,
  ...c1Grammar,
  ...phrases,
  ...pronunciation,
  ...academicVerbs,
  ...academicNouns,
  ...scienceNature,
  ...societyHistory,
  ...campusLife,
  ...linking,
];
